### PR TITLE
fix ChatWithoutForm state; closes #181

### LINKED ISSUE #181: Unable to remove preChat form from customChatWidget
Hello,

We are implementing the customChatWidget in our Salesforce customer portal which starts the AWS Connect Chat.  We do not want to use the preChat form - just have the chat window load when the chat icon is selected.  When the value under preChatForm for visible is changed to false, the chat icon fails to load.  Are there other places in this setup where the preChat form needs to be disabled and still have the chat icon be displayed?

### PR DESCRIPTION
**Pull request by spenlep-amzn**
*Issue #, if available:*
#181 

*Description of changes:*
Add missing variable `currentState` for the ChatWithoutForm component

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

File: customChatWidget/src/constants/index.js [hunk 1]
```diff
@@ -52,6 +52,11 @@ export const chatWithFormStates = {
   CHAT_WIDGET: 'chat'
 }
 
+export const chatWithoutFormStates = {
+ FORM: 'form',
+CHAT_WIDGET: 'chat'
```
Comment (doreechi) [inline customChatWidget/src/constants/index.js:57]: nit - formatting

**Review by doreechi — APPROVED** [review]
